final List<Map<String, dynamic>> quizQuestions = [
  {
    'word': 'Synonym for benevolent',
    'options': ['Kind', 'Cruel', 'Rich', 'Lazy'],
    'correctAnswer': 'Kind',
    'type': 'synonym',
  },

  {
    'word': 'Usage of benevolent',
    'options': [
      'The benevolent man donated generously to charity.',
      'He was malevolent and cruel to everyone.',
      'The lazy worker avoided tasks.',
      'She was rich and powerful.',
    ],
    'correctAnswer': 'The benevolent man donated generously to charity.',
    'type': 'usage',
  },
  {
    'word': 'Usage of diligent',
    'options': [
      'The diligent student completed her homework on time.',
      'The lazy student ignored his homework.',
      'He rushed through the homework carelessly.',
      'She forgot to do her homework.',
    ],
    'correctAnswer': 'The diligent student completed her homework on time.',
    'type': 'usage',
  },
  {
    'word': 'Usage of jovial',
    'options': [
      'The jovial host made everyone feel welcome.',
      'He was gloomy and sad all day.',
      'She was angry at the situation.',
      'He was tired and bored.',
    ],
    'correctAnswer': 'The jovial host made everyone feel welcome.',
    'type': 'usage',
  },
  {
    'word': 'Usage of resilient',
    'options': [
      'Despite the setback, she remained resilient.',
      'He gave up immediately.',
      'She was weak and fragile.',
      'He did nothing to recover.',
    ],
    'correctAnswer': 'Despite the setback, she remained resilient.',
    'type': 'usage',
  },
  {
    'word': 'Usage of meticulous',
    'options': [
      'The meticulous artist painted every detail perfectly.',
      'He did a sloppy job.',
      'She rushed without care.',
      'He ignored the instructions.',
    ],
    'correctAnswer': 'The meticulous artist painted every detail perfectly.',
    'type': 'usage',
  },
  {
    'word': 'Usage of gregarious',
    'options': [
      'The gregarious man enjoyed parties.',
      'She stayed alone all day.',
      'He avoided social events.',
      'She was shy and quiet.',
    ],
    'correctAnswer': 'The gregarious man enjoyed parties.',
    'type': 'usage',
  },
  {
    'word': 'Usage of hackneyed',
    'options': [
      'The hackneyed phrase was repeated in every speech.',
      'She used unique expressions.',
      'He was original in his work.',
      'The phrase was new and exciting.',
    ],
    'correctAnswer': 'The hackneyed phrase was repeated in every speech.',
    'type': 'usage',
  },
  {
    'word': 'Usage of judicious',
    'options': [
      'She made a judicious decision based on facts.',
      'He acted recklessly.',
      'She was careless in her choice.',
      'He ignored the evidence.',
    ],
    'correctAnswer': 'She made a judicious decision based on facts.',
    'type': 'usage',
  },
  {
    'word': 'Usage of audacious',
    'options': [
      'The audacious plan surprised everyone.',
      'He followed the rules carefully.',
      'She acted timidly.',
      'He avoided taking risks.',
    ],
    'correctAnswer': 'The audacious plan surprised everyone.',
    'type': 'usage',
  },
  {
    'word': 'Usage of magnanimous',
    'options': [
      'The magnanimous leader forgave his opponents.',
      'He held grudges forever.',
      'She was selfish and cruel.',
      'He never helped anyone.',
    ],
    'correctAnswer': 'The magnanimous leader forgave his opponents.',
    'type': 'usage',
  },
  {
    'word': 'Usage of nefarious',
    'options': [
      'The nefarious scheme was stopped by the police.',
      'He did a kind act for his neighbor.',
      'She helped her friend generously.',
      'He volunteered at the shelter.',
    ],
    'correctAnswer': 'The nefarious scheme was stopped by the police.',
    'type': 'usage',
  },
  {
    'word': 'Usage of perfidious',
    'options': [
      'He was perfidious and betrayed his friends.',
      'She remained loyal at all times.',
      'He always told the truth.',
      'She was trustworthy and honest.',
    ],
    'correctAnswer': 'He was perfidious and betrayed his friends.',
    'type': 'usage',
  },
  {
    'word': 'Meaning of resilient',
    'options': ['Able to recover quickly', 'Weak', 'Tired', 'Lazy'],
    'correctAnswer': 'Able to recover quickly',
    'type': 'definition',
  },
  {
    'word': 'Meaning of fortuitous',
    'options': ['Lucky', 'Unlucky', 'Planned', 'Expected'],
    'correctAnswer': 'Lucky',
    'type': 'definition',
  },

  {
    'word': 'Meaning of obfuscate',
    'options': ['To confuse', 'To clarify', 'To simplify', 'To reveal'],
    'correctAnswer': 'To confuse',
    'type': 'definition',
  },

  {
    'word': 'Usage of quixotic',
    'options': [
      'His quixotic ideas often failed.',
      'She made practical plans.',
      'He was realistic and careful.',
      'She solved problems efficiently.',
    ],
    'correctAnswer': 'His quixotic ideas often failed.',
    'type': 'usage',
  },
  {
    'word': 'Usage of reclusive',
    'options': [
      'The reclusive author avoided public events.',
      'He enjoyed social gatherings.',
      'She loved meeting new people.',
      'He was very outgoing and friendly.',
    ],
    'correctAnswer': 'The reclusive author avoided public events.',
    'type': 'usage',
  },
  {
    'word': 'Usage of temerity',
    'options': [
      'He had the temerity to challenge his boss.',
      'She was cautious in every move.',
      'He hesitated before acting.',
      'She avoided taking risks.',
    ],
    'correctAnswer': 'He had the temerity to challenge his boss.',
    'type': 'usage',
  },
  {
    'word': 'Meaning of resilient',
    'options': ['Able to recover quickly', 'Weak', 'Tired', 'Lazy'],
    'correctAnswer': 'Able to recover quickly',
    'type': 'definition',
  },
  {
    'word': 'Meaning of fortuitous',
    'options': ['Lucky', 'Unlucky', 'Planned', 'Expected'],
    'correctAnswer': 'Lucky',
    'type': 'definition',
  },

  {
    'word': 'Meaning of obfuscate',
    'options': ['To confuse', 'To clarify', 'To simplify', 'To reveal'],
    'correctAnswer': 'To confuse',
    'type': 'definition',
  },

  {
    'word': 'Usage of vacillate',
    'options': [
      'He vacillated between choices for hours.',
      'She made a firm decision immediately.',
      'He acted decisively.',
      'She chose quickly without thinking.',
    ],
    'correctAnswer': 'He vacillated between choices for hours.',
    'type': 'usage',
  },
  {
    'word': 'Usage of wane',
    'options': [
      'Interest in the project began to wane.',
      'Interest grew steadily.',
      'Engagement increased rapidly.',
      'Excitement was at its peak.',
    ],
    'correctAnswer': 'Interest in the project began to wane.',
    'type': 'usage',
  },
  {
    'word': 'Usage of xenophobia',
    'options': [
      'Xenophobia led to distrust of foreigners.',
      'He welcomed people from all cultures.',
      'She embraced diversity.',
      'The community celebrated newcomers.',
    ],
    'correctAnswer': 'Xenophobia led to distrust of foreigners.',
    'type': 'usage',
  },
  {
    'word': 'Usage of yoke',
    'options': [
      'The farmers yoked the oxen to plow the field.',
      'They worked independently.',
      'She freed the animals.',
      'He removed the harness.',
    ],
    'correctAnswer': 'The farmers yoked the oxen to plow the field.',
    'type': 'usage',
  },
  {
    'word': 'Usage of zeal',
    'options': [
      'She approached the project with great zeal.',
      'He was indifferent and lazy.',
      'She ignored her responsibilities.',
      'He lacked motivation.',
    ],
    'correctAnswer': 'She approached the project with great zeal.',
    'type': 'usage',
  },
  {
    'word': 'Usage of acumen',
    'options': [
      'His business acumen saved the company.',
      'She lacked insight.',
      'He was clueless about the deal.',
      'She made poor choices.',
    ],
    'correctAnswer': 'His business acumen saved the company.',
    'type': 'usage',
  },

  {
    'word': 'Antonym for benevolent',
    'options': ['Malevolent', 'Kind', 'Generous', 'Helpful'],
    'correctAnswer': 'Malevolent',
    'type': 'antonym',
  },
  {
    'word': 'Meaning of defiant',
    'options': ['Resisting authority', 'Obedient', 'Timid', 'Kind'],
    'correctAnswer': 'Resisting authority',
    'type': 'definition',
  },
  {
    'word': 'Usage of benevolent in a sentence',
    'options': [
      'The benevolent man donated generously to charity.',
      'He was malevolent and cruel to everyone.',
      'The lazy worker avoided tasks.',
      'She was rich and powerful.',
    ],
    'correctAnswer': 'The benevolent man donated generously to charity.',
    'type': 'usage',
  },
  {
    'word': 'Synonym for swift',
    'options': ['Fast', 'Slow', 'Lazy', 'Weak'],
    'correctAnswer': 'Fast',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for swift',
    'options': ['Slow', 'Fast', 'Quick', 'Rapid'],
    'correctAnswer': 'Slow',
    'type': 'antonym',
  },
  {
    'word': 'Meaning of ancient',
    'options': ['Very old', 'Modern', 'Young', 'New'],
    'correctAnswer': 'Very old',
    'type': 'definition',
  },
  {
    'word': 'Usage of diligent in a sentence',
    'options': [
      'The diligent student completed her homework on time.',
      'The lazy student ignored his homework.',
      'He rushed through the homework carelessly.',
      'She forgot to do her homework.',
    ],
    'correctAnswer': 'The diligent student completed her homework on time.',
    'type': 'usage',
  },
  {
    'word': 'Synonym for jovial',
    'options': ['Cheerful', 'Sad', 'Angry', 'Tired'],
    'correctAnswer': 'Cheerful',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for jovial',
    'options': ['Sad', 'Cheerful', 'Angry', 'Excited'],
    'correctAnswer': 'Sad',
    'type': 'antonym',
  },
  {
    'word': 'Meaning of exuberant',
    'options': ['Full of energy', 'Tired', 'Lazy', 'Sad'],
    'correctAnswer': 'Full of energy',
    'type': 'definition',
  },
  {
    'word': 'Synonym for concise',
    'options': ['Brief', 'Long', 'Verbose', 'Excessive'],
    'correctAnswer': 'Brief',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for concise',
    'options': ['Verbose', 'Brief', 'Short', 'Compact'],
    'correctAnswer': 'Verbose',
    'type': 'antonym',
  },
  {
    'word': 'Meaning of resilient',
    'options': ['Able to recover quickly', 'Weak', 'Tired', 'Slow'],
    'correctAnswer': 'Able to recover quickly',
    'type': 'definition',
  },
  {
    'word': 'Synonym for audacious',
    'options': ['Bold', 'Shy', 'Cautious', 'Weak'],
    'correctAnswer': 'Bold',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for audacious',
    'options': ['Timid', 'Bold', 'Courageous', 'Fearless'],
    'correctAnswer': 'Timid',
    'type': 'antonym',
  },
  {
    'word': 'Meaning of meticulous',
    'options': ['Extremely careful', 'Careless', 'Lazy', 'Rushed'],
    'correctAnswer': 'Extremely careful',
    'type': 'definition',
  },
  {
    'word': 'Synonym for elated',
    'options': ['Overjoyed', 'Sad', 'Angry', 'Tired'],
    'correctAnswer': 'Overjoyed',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for elated',
    'options': ['Depressed', 'Joyful', 'Excited', 'Happy'],
    'correctAnswer': 'Depressed',
    'type': 'antonym',
  },
  {
    'word': 'Meaning of ambiguous',
    'options': ['Unclear', 'Clear', 'Obvious', 'Simple'],
    'correctAnswer': 'Unclear',
    'type': 'definition',
  },
  {
    'word': 'Synonym for formidable',
    'options': ['Powerful', 'Weak', 'Small', 'Friendly'],
    'correctAnswer': 'Powerful',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for formidable',
    'options': ['Weak', 'Strong', 'Powerful', 'Fearsome'],
    'correctAnswer': 'Weak',
    'type': 'antonym',
  },
  {
    'word': 'Meaning of hasty',
    'options': ['Rushed', 'Slow', 'Careful', 'Delayed'],
    'correctAnswer': 'Rushed',
    'type': 'definition',
  },
  {
    'word': 'Synonym for lethargic',
    'options': ['Sluggish', 'Active', 'Energetic', 'Fast'],
    'correctAnswer': 'Sluggish',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for lethargic',
    'options': ['Active', 'Sluggish', 'Tired', 'Lazy'],
    'correctAnswer': 'Active',
    'type': 'antonym',
  },
  {
    'word': 'Meaning of obstinate',
    'options': ['Stubborn', 'Flexible', 'Agreeable', 'Weak'],
    'correctAnswer': 'Stubborn',
    'type': 'definition',
  },
  {
    'word': 'Meaning of iconoclast',
    'options': [
      'One who challenges tradition',
      'Follower',
      'Supporter',
      'Conformist',
    ],
    'correctAnswer': 'One who challenges tradition',
    'type': 'definition',
  },
  {
    'word': 'Meaning of kudos',
    'options': ['Praise', 'Criticism', 'Disrespect', 'Reproach'],
    'correctAnswer': 'Praise',
    'type': 'definition',
  },
  {
    'word': 'Meaning of lethargic',
    'options': ['Sluggish', 'Energetic', 'Active', 'Vigorous'],
    'correctAnswer': 'Sluggish',
    'type': 'definition',
  },
  {
    'word': 'Meaning of maverick',
    'options': [
      'Independent thinker',
      'Conformist',
      'Follower',
      'Traditionalist',
    ],
    'correctAnswer': 'Independent thinker',
    'type': 'definition',
  },
  {
    'word': 'Meaning of neophyte',
    'options': ['Beginner', 'Expert', 'Veteran', 'Master'],
    'correctAnswer': 'Beginner',
    'type': 'definition',
  },
  {
    'word': 'Meaning of obsequious',
    'options': ['Overly submissive', 'Dominant', 'Assertive', 'Independent'],
    'correctAnswer': 'Overly submissive',
    'type': 'definition',
  },
  {
    'word': 'Meaning of paragon',
    'options': ['Model of perfection', 'Flaw', 'Defect', 'Weakness'],
    'correctAnswer': 'Model of perfection',
    'type': 'definition',
  },
  {
    'word': 'Meaning of quagmire',
    'options': ['Difficult situation', 'Solution', 'Easy task', 'Advantage'],
    'correctAnswer': 'Difficult situation',
    'type': 'definition',
  },
  {
    'word': 'Meaning of recalcitrant',
    'options': ['Stubbornly resistant', 'Compliant', 'Obedient', 'Agreeable'],
    'correctAnswer': 'Stubbornly resistant',
    'type': 'definition',
  },
  {
    'word': 'Meaning of sanguine',
    'options': ['Optimistic', 'Pessimistic', 'Hopeless', 'Depressed'],
    'correctAnswer': 'Optimistic',
    'type': 'definition',
  },

  {
    'word': 'Synonym for pragmatic',
    'options': ['Practical', 'Theoretical', 'Useless', 'Lazy'],
    'correctAnswer': 'Practical',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for pragmatic',
    'options': ['Impractical', 'Practical', 'Useful', 'Logical'],
    'correctAnswer': 'Impractical',
    'type': 'antonym',
  },
  {
    'word': 'Meaning of wary',
    'options': ['Cautious', 'Careless', 'Brave', 'Bold'],
    'correctAnswer': 'Cautious',
    'type': 'definition',
  },
  {
    'word': 'Synonym for xenial',
    'options': ['Hospitable', 'Hostile', 'Rude', 'Unkind'],
    'correctAnswer': 'Hospitable',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for xenial',
    'options': ['Hostile', 'Friendly', 'Kind', 'Welcoming'],
    'correctAnswer': 'Hostile',
    'type': 'antonym',
  },
  {
    'word': 'Meaning of zealous',
    'options': ['Enthusiastic', 'Lazy', 'Tired', 'Indifferent'],
    'correctAnswer': 'Enthusiastic',
    'type': 'definition',
  },
  {
    'word': 'Synonym for candid',
    'options': ['Honest', 'Deceitful', 'Sneaky', 'False'],
    'correctAnswer': 'Honest',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for candid',
    'options': ['Deceitful', 'Honest', 'Open', 'Frank'],
    'correctAnswer': 'Deceitful',
    'type': 'antonym',
  },
  {
    'word': 'Meaning of fortuitous',
    'options': ['Lucky', 'Unlucky', 'Planned', 'Expected'],
    'correctAnswer': 'Lucky',
    'type': 'definition',
  },
  {
    'word': 'Synonym for gregarious',
    'options': ['Sociable', 'Shy', 'Reserved', 'Quiet'],
    'correctAnswer': 'Sociable',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for gregarious',
    'options': ['Shy', 'Sociable', 'Friendly', 'Talkative'],
    'correctAnswer': 'Shy',
    'type': 'antonym',
  },
  {
    'word': 'Meaning of hackneyed',
    'options': ['Overused', 'Original', 'Unique', 'Rare'],
    'correctAnswer': 'Overused',
    'type': 'definition',
  },
  {
    'word': 'Synonym for impetuous',
    'options': ['Impulsive', 'Careful', 'Cautious', 'Thoughtful'],
    'correctAnswer': 'Impulsive',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for impetuous',
    'options': ['Cautious', 'Impulsive', 'Reckless', 'Hasty'],
    'correctAnswer': 'Cautious',
    'type': 'antonym',
  },
  {
    'word': 'Synonym for benevolent',
    'options': ['Kind', 'Cruel', 'Rich', 'Lazy'],
    'correctAnswer': 'Kind',
    'type': 'synonym',
  },
  {
    'word': 'Meaning of resilient',
    'options': ['Able to recover quickly', 'Weak', 'Tired', 'Lazy'],
    'correctAnswer': 'Able to recover quickly',
    'type': 'definition',
  },
  {
    'word': 'Meaning of fortuitous',
    'options': ['Lucky', 'Unlucky', 'Planned', 'Expected'],
    'correctAnswer': 'Lucky',
    'type': 'definition',
  },

  {
    'word': 'Meaning of obfuscate',
    'options': ['To confuse', 'To clarify', 'To simplify', 'To reveal'],
    'correctAnswer': 'To confuse',
    'type': 'definition',
  },

  {
    'word': 'Synonym for swift',
    'options': ['Fast', 'Slow', 'Lazy', 'Weak'],
    'correctAnswer': 'Fast',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for jovial',
    'options': ['Cheerful', 'Sad', 'Angry', 'Tired'],
    'correctAnswer': 'Cheerful',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for benevolent',
    'options': ['Malevolent', 'Kind', 'Generous', 'Helpful'],
    'correctAnswer': 'Malevolent',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for swift',
    'options': ['Slow', 'Fast', 'Quick', 'Rapid'],
    'correctAnswer': 'Slow',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for jovial',
    'options': ['Sad', 'Cheerful', 'Angry', 'Excited'],
    'correctAnswer': 'Sad',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for diligent',
    'options': ['Lazy', 'Hardworking', 'Focused', 'Active'],
    'correctAnswer': 'Lazy',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for resilient',
    'options': ['Weak', 'Strong', 'Tough', 'Persistent'],
    'correctAnswer': 'Weak',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for audacious',
    'options': ['Timid', 'Bold', 'Courageous', 'Fearless'],
    'correctAnswer': 'Timid',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for meticulous',
    'options': ['Careless', 'Careful', 'Precise', 'Diligent'],
    'correctAnswer': 'Careless',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for exuberant',
    'options': ['Tired', 'Energetic', 'Joyful', 'Lively'],
    'correctAnswer': 'Tired',
    'type': 'antonym',
  },
  {
    'word': 'Synonym for diligent',
    'options': ['Hardworking', 'Lazy', 'Careless', 'Idle'],
    'correctAnswer': 'Hardworking',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for resilient',
    'options': ['Strong', 'Weak', 'Lazy', 'Tired'],
    'correctAnswer': 'Strong',
    'type': 'synonym',
  },
  {
    'word': 'Usage of affable',
    'options': [
      'The affable teacher was loved by all students.',
      'He was rude and unapproachable.',
      'She ignored everyone politely.',
      'He shouted at his classmates.',
    ],
    'correctAnswer': 'The affable teacher was loved by all students.',
    'type': 'usage',
  },
  {
    'word': 'Usage of belligerent',
    'options': [
      'The belligerent soldier argued with everyone.',
      'He was calm and peaceful.',
      'She mediated the conflict smoothly.',
      'They avoided confrontation.',
    ],
    'correctAnswer': 'The belligerent soldier argued with everyone.',
    'type': 'usage',
  },
  {
    'word': 'Usage of candid',
    'options': [
      'She gave a candid opinion during the meeting.',
      'He lied about his feelings.',
      'They avoided the topic entirely.',
      'She was secretive and evasive.',
    ],
    'correctAnswer': 'She gave a candid opinion during the meeting.',
    'type': 'usage',
  },
  {
    'word': 'Usage of deleterious',
    'options': [
      'Smoking has deleterious effects on health.',
      'It benefits your health greatly.',
      'It is neutral to your well-being.',
      'It has minor positive effects.',
    ],
    'correctAnswer': 'Smoking has deleterious effects on health.',
    'type': 'usage',
  },
  {
    'word': 'Usage of eclectic',
    'options': [
      'He has an eclectic taste in music.',
      'She listens to only one genre.',
      'He dislikes variety.',
      'She prefers repetitive choices.',
    ],
    'correctAnswer': 'He has an eclectic taste in music.',
    'type': 'usage',
  },
  {
    'word': 'Usage of fortitude',
    'options': [
      'She faced the challenges with great fortitude.',
      'He gave up immediately.',
      'She avoided all difficulties.',
      'He was weak and indecisive.',
    ],
    'correctAnswer': 'She faced the challenges with great fortitude.',
    'type': 'usage',
  },
  {
    'word': 'Synonym for temerity',
    'options': ['Boldness', 'Caution', 'Fear', 'Shyness'],
    'correctAnswer': 'Boldness',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for ubiquitous',
    'options': ['Everywhere', 'Rare', 'Limited', 'Hidden'],
    'correctAnswer': 'Everywhere',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for vacillate',
    'options': ['Waver', 'Decide', 'Persist', 'Continue'],
    'correctAnswer': 'Waver',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for wane',
    'options': ['Decrease', 'Increase', 'Grow', 'Expand'],
    'correctAnswer': 'Decrease',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for xenophobia',
    'options': [
      'Fear of foreigners',
      'Love of foreigners',
      'Acceptance',
      'Friendship',
    ],
    'correctAnswer': 'Fear of foreigners',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for yoke',
    'options': ['Bind', 'Free', 'Release', 'Unite'],
    'correctAnswer': 'Bind',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for zeal',
    'options': ['Passion', 'Apathy', 'Indifference', 'Laziness'],
    'correctAnswer': 'Passion',
    'type': 'synonym',
  },
  {
    'word': 'Usage of garrulous',
    'options': [
      'The garrulous man could not stop talking.',
      'He remained silent all day.',
      'She only spoke when necessary.',
      'He was very reserved.',
    ],
    'correctAnswer': 'The garrulous man could not stop talking.',
    'type': 'usage',
  },
  {
    'word': 'Usage of hegemony',
    'options': [
      'The country maintained its cultural hegemony.',
      'They had no influence over neighbors.',
      'The local culture dominated them.',
      'They adopted foreign customs fully.',
    ],
    'correctAnswer': 'The country maintained its cultural hegemony.',
    'type': 'usage',
  },
  {
    'word': 'Usage of impetuous',
    'options': [
      'His impetuous actions caused trouble.',
      'He carefully analyzed everything.',
      'She acted cautiously.',
      'He avoided risky decisions.',
    ],
    'correctAnswer': 'His impetuous actions caused trouble.',
    'type': 'usage',
  },
  {
    'word': 'Usage of judicious',
    'options': [
      'She made a judicious choice in investments.',
      'He spent money recklessly.',
      'She ignored the advice.',
      'He acted impulsively without thinking.',
    ],
    'correctAnswer': 'She made a judicious choice in investments.',
    'type': 'usage',
  },
  {
    'word': 'Usage of kinetic',
    'options': [
      'The kinetic energy of the moving car was high.',
      'The car was at rest.',
      'The energy was potential only.',
      'There was no motion involved.',
    ],
    'correctAnswer': 'The kinetic energy of the moving car was high.',
    'type': 'usage',
  },
  {
    'word': 'Usage of lucid',
    'options': [
      'He gave a lucid explanation of the problem.',
      'She confused everyone with vague words.',
      'He was unclear and ambiguous.',
      'She remained silent throughout.',
    ],
    'correctAnswer': 'He gave a lucid explanation of the problem.',
    'type': 'usage',
  },
  {
    'word': 'Usage of magnanimous',
    'options': [
      'She was magnanimous in victory.',
      'He gossiped spitefully about his rivals.',
      'She sought revenge.',
      'He refused to forgive.',
    ],
    'correctAnswer': 'She was magnanimous in victory.',
    'type': 'usage',
  },
  {
    'word': 'Synonym for obfuscate',
    'options': ['Confuse', 'Clarify', 'Explain', 'Simplify'],
    'correctAnswer': 'Confuse',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for perfidious',
    'options': ['Treacherous', 'Loyal', 'Trustworthy', 'Faithful'],
    'correctAnswer': 'Treacherous',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for quixotic',
    'options': ['Idealistic', 'Realistic', 'Practical', 'Sensible'],
    'correctAnswer': 'Idealistic',
    'type': 'synonym',
  },
  {
    'word': 'Meaning of magnanimous',
    'options': ['Generous', 'Selfish', 'Greedy', 'Cruel'],
    'correctAnswer': 'Generous',
    'type': 'definition',
  },
  {
    'word': 'Synonym for idiosyncrasy',
    'options': ['Unique trait', 'Common habit', 'Normal behavior', 'Weakness'],
    'correctAnswer': 'Unique trait',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for juxtapose',
    'options': ['Place side by side', 'Separate', 'Ignore', 'Move away'],
    'correctAnswer': 'Place side by side',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for laconic',
    'options': ['Brief', 'Wordy', 'Talkative', 'Verbose'],
    'correctAnswer': 'Brief',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for mendacious',
    'options': ['Dishonest', 'Honest', 'Truthful', 'Sincere'],
    'correctAnswer': 'Dishonest',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for nefarious',
    'options': ['Wicked', 'Good', 'Honorable', 'Kind'],
    'correctAnswer': 'Wicked',
    'type': 'synonym',
  },
  {
    'word': 'Usage of nonchalant',
    'options': [
      'He acted nonchalant despite the chaos.',
      'She panicked immediately.',
      'He stressed out.',
      'She reacted nervously.',
    ],
    'correctAnswer': 'He acted nonchalant despite the chaos.',
    'type': 'usage',
  },
  {
    'word': 'Usage of obsequious',
    'options': [
      'The obsequious assistant flattered his boss constantly.',
      'He challenged authority openly.',
      'She ignored her supervisor.',
      'He acted independently.',
    ],
    'correctAnswer': 'The obsequious assistant flattered his boss constantly.',
    'type': 'usage',
  },
  {
    'word': 'Usage of pragmatic',
    'options': [
      'She took a pragmatic approach to solving problems.',
      'He ignored the issue entirely.',
      'She acted emotionally without logic.',
      'He avoided practical solutions.',
    ],
    'correctAnswer': 'She took a pragmatic approach to solving problems.',
    'type': 'usage',
  },
  {
    'word': 'Usage of querulous',
    'options': [
      'The querulous child complained about everything.',
      'He accepted the situation calmly.',
      'She ignored minor issues.',
      'He praised everyone constantly.',
    ],
    'correctAnswer': 'The querulous child complained about everything.',
    'type': 'usage',
  },
  {
    'word': 'Synonym for obfuscate',
    'options': ['Confuse', 'Clarify', 'Explain', 'Simplify'],
    'correctAnswer': 'Confuse',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for perfidious',
    'options': ['Treacherous', 'Loyal', 'Trustworthy', 'Faithful'],
    'correctAnswer': 'Treacherous',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for quixotic',
    'options': ['Idealistic', 'Realistic', 'Practical', 'Sensible'],
    'correctAnswer': 'Idealistic',
    'type': 'synonym',
  },
  {
    'word': 'Meaning of magnanimous',
    'options': ['Generous', 'Selfish', 'Greedy', 'Cruel'],
    'correctAnswer': 'Generous',
    'type': 'definition',
  },
  {
    'word': 'Usage of recalcitrant',
    'options': [
      'The recalcitrant employee refused to follow orders.',
      'He obeyed instructions willingly.',
      'She complied easily.',
      'He was cooperative.',
    ],
    'correctAnswer': 'The recalcitrant employee refused to follow orders.',
    'type': 'usage',
  },
  {
    'word': 'Usage of sagacious',
    'options': [
      'The sagacious leader guided his team wisely.',
      'He made reckless decisions.',
      'She acted without thought.',
      'He was foolish in judgment.',
    ],
    'correctAnswer': 'The sagacious leader guided his team wisely.',
    'type': 'usage',
  },
  {
    'word': 'Usage of terse',
    'options': [
      'He gave a terse reply to the question.',
      'She elaborated excessively.',
      'He explained at length.',
      'She provided detailed information.',
    ],
    'correctAnswer': 'He gave a terse reply to the question.',
    'type': 'usage',
  },
  {
    'word': 'Usage of ubiquitous',
    'options': [
      'Smartphones are ubiquitous these days.',
      'They are rare and uncommon.',
      'Few people own them.',
      'They are almost nonexistent.',
    ],
    'correctAnswer': 'Smartphones are ubiquitous these days.',
    'type': 'usage',
  },
  {
    'word': 'Usage of vicarious',
    'options': [
      'He lived vicariously through his friend’s adventures.',
      'He experienced everything personally.',
      'She avoided living through others.',
      'He ignored his friend’s experiences.',
    ],
    'correctAnswer': 'He lived vicariously through his friend’s adventures.',
    'type': 'usage',
  },
  {
    'word': 'Antonym for pragmatic',
    'options': ['Impractical', 'Practical', 'Logical', 'Useful'],
    'correctAnswer': 'Impractical',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for gregarious',
    'options': ['Shy', 'Sociable', 'Friendly', 'Talkative'],
    'correctAnswer': 'Shy',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for fortuitous',
    'options': ['Unlucky', 'Lucky', 'Planned', 'Expected'],
    'correctAnswer': 'Unlucky',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for impetuous',
    'options': ['Cautious', 'Impulsive', 'Reckless', 'Hasty'],
    'correctAnswer': 'Cautious',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for keen',
    'options': ['Indifferent', 'Eager', 'Excited', 'Happy'],
    'correctAnswer': 'Indifferent',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for loquacious',
    'options': ['Silent', 'Talkative', 'Chatty', 'Verbose'],
    'correctAnswer': 'Silent',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for magnanimous',
    'options': ['Selfish', 'Generous', 'Kind', 'Helpful'],
    'correctAnswer': 'Selfish',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for obstinate',
    'options': ['Flexible', 'Stubborn', 'Rigid', 'Strong'],
    'correctAnswer': 'Flexible',
    'type': 'antonym',
  },
  {
    'word': 'Usage of wistful',
    'options': [
      'She felt wistful thinking about the past.',
      'He was completely indifferent.',
      'She was fully content.',
      'He ignored memories.',
    ],
    'correctAnswer': 'She felt wistful thinking about the past.',
    'type': 'usage',
  },
  {
    'word': 'Antonym for sagacious',
    'options': ['Foolish', 'Wise', 'Intelligent', 'Smart'],
    'correctAnswer': 'Foolish',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for ubiquitous',
    'options': ['Rare', 'Everywhere', 'Common', 'Present'],
    'correctAnswer': 'Rare',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for venerate',
    'options': ['Despise', 'Respect', 'Honor', 'Admire'],
    'correctAnswer': 'Despise',
    'type': 'antonym',
  },

  {
    'word': 'Antonym for laconic',
    'options': ['Wordy', 'Brief', 'Concise', 'Terse'],
    'correctAnswer': 'Wordy',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for mendacious',
    'options': ['Honest', 'Dishonest', 'False', 'Untruthful'],
    'correctAnswer': 'Honest',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for nefarious',
    'options': ['Good', 'Wicked', 'Evil', 'Vicious'],
    'correctAnswer': 'Good',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for obfuscate',
    'options': ['Clarify', 'Confuse', 'Complicate', 'Bewilder'],
    'correctAnswer': 'Clarify',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for perfidious',
    'options': ['Loyal', 'Treacherous', 'Faithless', 'Unfaithful'],
    'correctAnswer': 'Loyal',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for quixotic',
    'options': ['Realistic', 'Idealistic', 'Impractical', 'Romantic'],
    'correctAnswer': 'Realistic',
    'type': 'antonym',
  },
  {
    'word': 'Usage of xenial',
    'options': [
      'The hosts were xenial to all visitors.',
      'They were rude to guests.',
      'She ignored the newcomers.',
      'He refused to welcome anyone.',
    ],
    'correctAnswer': 'The hosts were xenial to all visitors.',
    'type': 'usage',
  },
  {
    'word': 'Usage of yielding',
    'options': [
      'He was yielding in negotiations.',
      'She was inflexible.',
      'He refused to compromise.',
      'She was stubborn.',
    ],
    'correctAnswer': 'He was yielding in negotiations.',
    'type': 'usage',
  },
  {
    'word': 'Usage of zealous',
    'options': [
      'She was zealous in her studies.',
      'He was indifferent to learning.',
      'She ignored her work.',
      'He avoided responsibilities.',
    ],
    'correctAnswer': 'She was zealous in her studies.',
    'type': 'usage',
  },
  {
    'word': 'Usage of ameliorate',
    'options': [
      'The reforms helped ameliorate living conditions.',
      'They worsened the situation.',
      'No change occurred.',
      'The conditions deteriorated.',
    ],
    'correctAnswer': 'The reforms helped ameliorate living conditions.',
    'type': 'usage',
  },
  {
    'word': 'Usage of belligerent',
    'options': [
      'The belligerent nations refused to negotiate.',
      'They worked together peacefully.',
      'The conflict was resolved quickly.',
      'They avoided confrontation.',
    ],
    'correctAnswer': 'The belligerent nations refused to negotiate.',
    'type': 'usage',
  },
  {
    'word': 'Usage of candor',
    'options': [
      'Her candor impressed everyone.',
      'She lied constantly.',
      'He hid the truth.',
      'They avoided honesty.',
    ],
    'correctAnswer': 'Her candor impressed everyone.',
    'type': 'usage',
  },
  {
    'word': 'Usage of despondent',
    'options': [
      'He felt despondent after losing the match.',
      'He was cheerful and happy.',
      'She was optimistic.',
      'They celebrated excitedly.',
    ],
    'correctAnswer': 'He felt despondent after losing the match.',
    'type': 'usage',
  },
  {
    'word': 'Usage of ebullient',
    'options': [
      'The ebullient crowd cheered loudly.',
      'They were silent and gloomy.',
      'The audience left quietly.',
      'The group was indifferent.',
    ],
    'correctAnswer': 'The ebullient crowd cheered loudly.',
    'type': 'usage',
  },
  {
    'word': 'Usage of facetious',
    'options': [
      'He made a facetious comment during the meeting.',
      'He spoke seriously and formally.',
      'She avoided jokes.',
      'They acted solemnly.',
    ],
    'correctAnswer': 'He made a facetious comment during the meeting.',
    'type': 'usage',
  },
  {
    'word': 'Usage of gregarious',
    'options': [
      'The gregarious student enjoyed group projects.',
      'He avoided all social interactions.',
      'She preferred solitude.',
      'They ignored their classmates.',
    ],
    'correctAnswer': 'The gregarious student enjoyed group projects.',
    'type': 'usage',
  },
  {
    'word': 'Usage of haughty',
    'options': [
      'The haughty noble looked down on everyone.',
      'She treated everyone equally.',
      'He acted humbly.',
      'They showed respect.',
    ],
    'correctAnswer': 'The haughty noble looked down on everyone.',
    'type': 'usage',
  },
  {
    'word': 'Usage of impugn',
    'options': [
      'He tried to impugn her character.',
      'He praised her honestly.',
      'She was trusted by all.',
      'He supported her openly.',
    ],
    'correctAnswer': 'He tried to impugn her character.',
    'type': 'usage',
  },
  {
    'word': 'Usage of jaded',
    'options': [
      'She felt jaded after years of work.',
      'He was enthusiastic and fresh.',
      'They were motivated and energetic.',
      'She approached work eagerly.',
    ],
    'correctAnswer': 'She felt jaded after years of work.',
    'type': 'usage',
  },
  {
    'word': 'Usage of laconic',
    'options': [
      'His laconic reply surprised everyone.',
      'He spoke excessively.',
      'She gave a long-winded explanation.',
      'They elaborated endlessly.',
    ],
    'correctAnswer': 'His laconic reply surprised everyone.',
    'type': 'usage',
  },
  {
    'word': 'Usage of maudlin',
    'options': [
      'He became maudlin after the movie.',
      'She was emotionally stable.',
      'He remained unaffected.',
      'They were indifferent to events.',
    ],
    'correctAnswer': 'He became maudlin after the movie.',
    'type': 'usage',
  },
  {
    'word': 'Antonym for whimsical',
    'options': ['Serious', 'Playful', 'Fun', 'Jovial'],
    'correctAnswer': 'Serious',
    'type': 'antonym',
  },
  {
    'word': 'Synonym for enervate',
    'options': ['Weaken', 'Strengthen', 'Energize', 'Support'],
    'correctAnswer': 'Weaken',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for fastidious',
    'options': ['Attentive', 'Careless', 'Negligent', 'Lazy'],
    'correctAnswer': 'Attentive',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for garrulous',
    'options': ['Talkative', 'Quiet', 'Reserved', 'Silent'],
    'correctAnswer': 'Talkative',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for sanguine',
    'options': ['Pessimistic', 'Optimistic', 'Hopeful', 'Cheerful'],
    'correctAnswer': 'Pessimistic',
    'type': 'antonym',
  },

  {
    'word': 'Meaning of magnanimous',
    'options': ['Generous', 'Selfish', 'Greedy', 'Cruel'],
    'correctAnswer': 'Generous',
    'type': 'definition',
  },
  {
    'word': 'Meaning of nefarious',
    'options': ['Wicked', 'Good', 'Kind', 'Honest'],
    'correctAnswer': 'Wicked',
    'type': 'definition',
  },

  {
    'word': 'Meaning of nefarious',
    'options': ['Wicked', 'Good', 'Kind', 'Honest'],
    'correctAnswer': 'Wicked',
    'type': 'definition',
  },

  {
    'word': 'Antonym for sanguine',
    'options': ['Pessimistic', 'Optimistic', 'Hopeful', 'Cheerful'],
    'correctAnswer': 'Pessimistic',
    'type': 'antonym',
  },
  {
    'word': 'Synonym for hegemony',
    'options': ['Dominance', 'Weakness', 'Powerless', 'Subordinate'],
    'correctAnswer': 'Dominance',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for iconoclast',
    'options': ['Rebel', 'Follower', 'Supporter', 'Conformist'],
    'correctAnswer': 'Rebel',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for juxtapose',
    'options': ['Compare', 'Separate', 'Divide', 'Ignore'],
    'correctAnswer': 'Compare',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for kudos',
    'options': ['Praise', 'Criticism', 'Blame', 'Disrespect'],
    'correctAnswer': 'Praise',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for alacrity',
    'options': ['Reluctance', 'Eagerness', 'Excitement', 'Joy'],
    'correctAnswer': 'Reluctance',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for cacophony',
    'options': ['Harmony', 'Noise', 'Discord', 'Clamor'],
    'correctAnswer': 'Harmony',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for deleterious',
    'options': ['Beneficial', 'Harmful', 'Detrimental', 'Dangerous'],
    'correctAnswer': 'Beneficial',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for ephemeral',
    'options': ['Permanent', 'Short-lived', 'Transient', 'Fleeting'],
    'correctAnswer': 'Permanent',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for fastidious',
    'options': ['Careless', 'Attentive', 'Meticulous', 'Fussy'],
    'correctAnswer': 'Careless',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for garrulous',
    'options': ['Silent', 'Talkative', 'Chatty', 'Verbose'],
    'correctAnswer': 'Silent',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for harbinger',
    'options': ['Follower', 'Leader', 'Forerunner', 'Messenger'],
    'correctAnswer': 'Follower',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for idiosyncrasy',
    'options': ['Common trait', 'Unique trait', 'Quirk', 'Characteristic'],
    'correctAnswer': 'Common trait',
    'type': 'antonym',
  },
  {
    'word': 'Synonym for lethargic',
    'options': ['Tired', 'Energetic', 'Active', 'Alert'],
    'correctAnswer': 'Tired',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for maverick',
    'options': ['Independent', 'Conformist', 'Follower', 'Obedient'],
    'correctAnswer': 'Independent',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for neophyte',
    'options': ['Beginner', 'Expert', 'Skilled', 'Veteran'],
    'correctAnswer': 'Beginner',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for sanguine',
    'options': ['Pessimistic', 'Optimistic', 'Hopeful', 'Cheerful'],
    'correctAnswer': 'Pessimistic',
    'type': 'antonym',
  },

  {
    'word': 'Meaning of magnanimous',
    'options': ['Generous', 'Selfish', 'Greedy', 'Cruel'],
    'correctAnswer': 'Generous',
    'type': 'definition',
  },
  {
    'word': 'Meaning of nefarious',
    'options': ['Wicked', 'Good', 'Kind', 'Honest'],
    'correctAnswer': 'Wicked',
    'type': 'definition',
  },

  {
    'word': 'Meaning of nefarious',
    'options': ['Wicked', 'Good', 'Kind', 'Honest'],
    'correctAnswer': 'Wicked',
    'type': 'definition',
  },

  {
    'word': 'Antonym for sanguine',
    'options': ['Pessimistic', 'Optimistic', 'Hopeful', 'Cheerful'],
    'correctAnswer': 'Pessimistic',
    'type': 'antonym',
  },
  {
    'word': 'Synonym for obsequious',
    'options': ['Submissive', 'Dominant', 'Rebellious', 'Independent'],
    'correctAnswer': 'Submissive',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for paragon',
    'options': ['Model', 'Flaw', 'Defect', 'Weakness'],
    'correctAnswer': 'Model',
    'type': 'synonym',
  },

  {
    'word': 'Synonym for quagmire',
    'options': ['Dilemma', 'Solution', 'Answer', 'Resolution'],
    'correctAnswer': 'Dilemma',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for recalcitrant',
    'options': ['Disobedient', 'Compliant', 'Obedient', 'Agreeable'],
    'correctAnswer': 'Disobedient',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for sanguine',
    'options': ['Optimistic', 'Pessimistic', 'Negative', 'Hopeless'],
    'correctAnswer': 'Optimistic',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for juxtapose',
    'options': ['Separate', 'Combine', 'Compare', 'Join'],
    'correctAnswer': 'Separate',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for reclusive',
    'options': ['Sociable', 'Solitary', 'Isolated', 'Alone'],
    'correctAnswer': 'Sociable',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for temerity',
    'options': ['Caution', 'Boldness', 'Bravery', 'Audacity'],
    'correctAnswer': 'Caution',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for vacillate',
    'options': ['Decide', 'Waver', 'Hesitate', 'Fluctuate'],
    'correctAnswer': 'Decide',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for wane',
    'options': ['Increase', 'Decrease', 'Diminish', 'Shrink'],
    'correctAnswer': 'Increase',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for xenophobia',
    'options': ['Acceptance', 'Fear of foreigners', 'Prejudice', 'Hatred'],
    'correctAnswer': 'Acceptance',
    'type': 'antonym',
  },
  {
    'word': 'Meaning of perfidious',
    'options': ['Treacherous', 'Loyal', 'Faithful', 'Honest'],
    'correctAnswer': 'Treacherous',
    'type': 'definition',
  },
  {
    'word': 'Meaning of quixotic',
    'options': ['Unrealistic', 'Practical', 'Logical', 'Rational'],
    'correctAnswer': 'Unrealistic',
    'type': 'definition',
  },
  {
    'word': 'Antonym for recalcitrant',
    'options': ['Compliant', 'Disobedient', 'Obstinate', 'Defiant'],
    'correctAnswer': 'Compliant',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for sanguine',
    'options': ['Pessimistic', 'Optimistic', 'Hopeful', 'Cheerful'],
    'correctAnswer': 'Pessimistic',
    'type': 'antonym',
  },
  {
    'word': 'Meaning of reclusive',
    'options': ['Solitary', 'Sociable', 'Friendly', 'Talkative'],
    'correctAnswer': 'Solitary',
    'type': 'definition',
  },

  {
    'word': 'Antonym for neophyte',
    'options': ['Expert', 'Beginner', 'Novice', 'Amateur'],
    'correctAnswer': 'Expert',
    'type': 'antonym',
  },
  {
    'word': 'Meaning of temerity',
    'options': ['Reckless boldness', 'Caution', 'Fear', 'Hesitation'],
    'correctAnswer': 'Reckless boldness',
    'type': 'definition',
  },
  {
    'word': 'Meaning of vacillate',
    'options': [
      'Waver between options',
      'Decide firmly',
      'Act quickly',
      'Choose one',
    ],
    'correctAnswer': 'Waver between options',
    'type': 'definition',
  },
  {
    'word': 'Meaning of wane',
    'options': ['Decrease gradually', 'Increase', 'Grow', 'Expand'],
    'correctAnswer': 'Decrease gradually',
    'type': 'definition',
  },
  {
    'word': 'Meaning of xenophobia',
    'options': ['Fear of foreigners', 'Acceptance', 'Love', 'Respect'],
    'correctAnswer': 'Fear of foreigners',
    'type': 'definition',
  },
  {
    'word': 'Meaning of yoke',
    'options': ['To bind', 'To free', 'To release', 'To remove'],
    'correctAnswer': 'To bind',
    'type': 'definition',
  },
  {
    'word': 'Meaning of zeal',
    'options': ['Great enthusiasm', 'Apathy', 'Indifference', 'Disinterest'],
    'correctAnswer': 'Great enthusiasm',
    'type': 'definition',
  },
  {
    'word': 'Meaning of acumen',
    'options': ['Keen insight', 'Ignorance', 'Stupidity', 'Confusion'],
    'correctAnswer': 'Keen insight',
    'type': 'definition',
  },
  {
    'word': 'Meaning of belligerent',
    'options': ['Hostile', 'Friendly', 'Calm', 'Peaceful'],
    'correctAnswer': 'Hostile',
    'type': 'definition',
  },
  {
    'word': 'Meaning of capricious',
    'options': ['Fickle', 'Stable', 'Steady', 'Reliable'],
    'correctAnswer': 'Fickle',
    'type': 'definition',
  },
  {
    'word': 'Meaning of diffident',
    'options': ['Shy', 'Confident', 'Bold', 'Assertive'],
    'correctAnswer': 'Shy',
    'type': 'definition',
  },
  {
    'word': 'Meaning of enervate',
    'options': ['Weaken', 'Strengthen', 'Invigorate', 'Energize'],
    'correctAnswer': 'Weaken',
    'type': 'definition',
  },
  {
    'word': 'Meaning of hegemony',
    'options': ['Dominance', 'Subordination', 'Weakness', 'Insignificance'],
    'correctAnswer': 'Dominance',
    'type': 'definition',
  },

  {
    'word': 'Antonym for yoke',
    'options': ['Release', 'Bind', 'Attach', 'Tie'],
    'correctAnswer': 'Release',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for zeal',
    'options': ['Apathy', 'Passion', 'Energy', 'Enthusiasm'],
    'correctAnswer': 'Apathy',
    'type': 'antonym',
  },
  {
    'word': 'Meaning of defiant',
    'options': ['Resisting authority', 'Obedient', 'Timid', 'Kind'],
    'correctAnswer': 'Resisting authority',
    'type': 'definition',
  },
  {
    'word': 'Meaning of ancient',
    'options': ['Very old', 'Modern', 'Young', 'New'],
    'correctAnswer': 'Very old',
    'type': 'definition',
  },
  {
    'word': 'Meaning of ambivalent',
    'options': ['Having mixed feelings', 'Certain', 'Confident', 'Decisive'],
    'correctAnswer': 'Having mixed feelings',
    'type': 'definition',
  },
  {
    'word': 'Meaning of obstinate',
    'options': ['Stubborn', 'Flexible', 'Agreeable', 'Weak'],
    'correctAnswer': 'Stubborn',
    'type': 'definition',
  },
  {
    'word': 'Meaning of wary',
    'options': ['Cautious', 'Careless', 'Brave', 'Bold'],
    'correctAnswer': 'Cautious',
    'type': 'definition',
  },
  {
    'word': 'Meaning of zealous',
    'options': ['Enthusiastic', 'Lazy', 'Tired', 'Indifferent'],
    'correctAnswer': 'Enthusiastic',
    'type': 'definition',
  },
  {
    'word': 'Antonym for acumen',
    'options': ['Ignorance', 'Insight', 'Intelligence', 'Wisdom'],
    'correctAnswer': 'Ignorance',
    'type': 'antonym',
  },
  {
    'word': 'Synonym for magnanimous',
    'options': ['Generous', 'Selfish', 'Greedy', 'Rude'],
    'correctAnswer': 'Generous',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for obstinate',
    'options': ['Stubborn', 'Flexible', 'Agreeable', 'Weak'],
    'correctAnswer': 'Stubborn',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for sagacious',
    'options': ['Wise', 'Foolish', 'Careless', 'Impulsive'],
    'correctAnswer': 'Wise',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for ubiquitous',
    'options': ['Everywhere', 'Rare', 'Unusual', 'Hidden'],
    'correctAnswer': 'Everywhere',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for venerate',
    'options': ['Respect', 'Ignore', 'Hate', 'Despise'],
    'correctAnswer': 'Respect',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for whimsical',
    'options': ['Playful', 'Serious', 'Boring', 'Dull'],
    'correctAnswer': 'Playful',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for alacrity',
    'options': ['Eagerness', 'Reluctance', 'Tiredness', 'Sadness'],
    'correctAnswer': 'Eagerness',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for cacophony',
    'options': ['Harsh noise', 'Silence', 'Melody', 'Calm'],
    'correctAnswer': 'Harsh noise',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for deleterious',
    'options': ['Harmful', 'Helpful', 'Useful', 'Beneficial'],
    'correctAnswer': 'Harmful',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for ephemeral',
    'options': ['Short-lived', 'Permanent', 'Endless', 'Long'],
    'correctAnswer': 'Short-lived',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for fastidious',
    'options': ['Very attentive', 'Careless', 'Lazy', 'Messy'],
    'correctAnswer': 'Very attentive',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for belligerent',
    'options': ['Friendly', 'Hostile', 'Aggressive', 'Combative'],
    'correctAnswer': 'Friendly',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for capricious',
    'options': ['Stable', 'Fickle', 'Unpredictable', 'Changeable'],
    'correctAnswer': 'Stable',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for diffident',
    'options': ['Confident', 'Shy', 'Reserved', 'Timid'],
    'correctAnswer': 'Confident',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for enervate',
    'options': ['Strengthen', 'Weaken', 'Fatigue', 'Exhaust'],
    'correctAnswer': 'Strengthen',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for hegemony',
    'options': ['Subordinate', 'Dominance', 'Power', 'Control'],
    'correctAnswer': 'Subordinate',
    'type': 'antonym',
  },
  {
    'word': 'Synonym for reclusive',
    'options': ['Solitary', 'Sociable', 'Outgoing', 'Friendly'],
    'correctAnswer': 'Solitary',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for sagacious',
    'options': ['Wise', 'Foolish', 'Impulsive', 'Ignorant'],
    'correctAnswer': 'Wise',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for temerity',
    'options': ['Boldness', 'Caution', 'Fear', 'Shyness'],
    'correctAnswer': 'Boldness',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for ubiquitous',
    'options': ['Everywhere', 'Rare', 'Limited', 'Hidden'],
    'correctAnswer': 'Everywhere',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for vacillate',
    'options': ['Waver', 'Decide', 'Persist', 'Continue'],
    'correctAnswer': 'Waver',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for recalcitrant',
    'options': ['Compliant', 'Disobedient', 'Obstinate', 'Defiant'],
    'correctAnswer': 'Compliant',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for iconoclast',
    'options': ['Follower', 'Rebel', 'Opposer', 'Challenger'],
    'correctAnswer': 'Follower',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for kudos',
    'options': ['Criticism', 'Praise', 'Honor', 'Compliment'],
    'correctAnswer': 'Criticism',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for lethargic',
    'options': ['Energetic', 'Tired', 'Sleepy', 'Lazy'],
    'correctAnswer': 'Energetic',
    'type': 'antonym',
  },
  {
    'word': 'Synonym for wane',
    'options': ['Decrease', 'Increase', 'Grow', 'Expand'],
    'correctAnswer': 'Decrease',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for xenophobia',
    'options': [
      'Fear of foreigners',
      'Love of foreigners',
      'Acceptance',
      'Friendship',
    ],
    'correctAnswer': 'Fear of foreigners',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for yoke',
    'options': ['Bind', 'Free', 'Release', 'Unite'],
    'correctAnswer': 'Bind',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for zeal',
    'options': ['Passion', 'Apathy', 'Indifference', 'Laziness'],
    'correctAnswer': 'Passion',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for acumen',
    'options': ['Insight', 'Ignorance', 'Foolishness', 'Naivety'],
    'correctAnswer': 'Insight',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for belligerent',
    'options': ['Hostile', 'Friendly', 'Kind', 'Gentle'],
    'correctAnswer': 'Hostile',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for capricious',
    'options': ['Fickle', 'Stable', 'Predictable', 'Constant'],
    'correctAnswer': 'Fickle',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for diffident',
    'options': ['Shy', 'Bold', 'Confident', 'Outgoing'],
    'correctAnswer': 'Shy',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for maverick',
    'options': ['Conformist', 'Independent', 'Rebel', 'Nonconformist'],
    'correctAnswer': 'Conformist',
    'type': 'antonym',
  },
  {
    'word': 'Synonym for audacious',
    'options': ['Bold', 'Shy', 'Cautious', 'Weak'],
    'correctAnswer': 'Bold',
    'type': 'synonym',
  },
  {
    'word': 'Meaning of judicious',
    'options': ['Wise', 'Foolish', 'Careless', 'Impulsive'],
    'correctAnswer': 'Wise',
    'type': 'definition',
  },
  {
    'word': 'Synonym for keen',
    'options': ['Eager', 'Lazy', 'Disinterested', 'Indifferent'],
    'correctAnswer': 'Eager',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for meticulous',
    'options': ['Careful', 'Sloppy', 'Lazy', 'Rushed'],
    'correctAnswer': 'Careful',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for obsequious',
    'options': ['Dominant', 'Submissive', 'Obedient', 'Servile'],
    'correctAnswer': 'Dominant',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for paragon',
    'options': ['Flaw', 'Model', 'Example', 'Ideal'],
    'correctAnswer': 'Flaw',
    'type': 'antonym',
  },
  {
    'word': 'Antonym for quagmire',
    'options': ['Solution', 'Dilemma', 'Problem', 'Difficulty'],
    'correctAnswer': 'Solution',
    'type': 'antonym',
  },
  {
    'word': 'Synonym for exuberant',
    'options': ['Energetic', 'Tired', 'Sad', 'Lazy'],
    'correctAnswer': 'Energetic',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for pragmatic',
    'options': ['Practical', 'Theoretical', 'Useless', 'Lazy'],
    'correctAnswer': 'Practical',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for gregarious',
    'options': ['Sociable', 'Shy', 'Reserved', 'Quiet'],
    'correctAnswer': 'Sociable',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for fortuitous',
    'options': ['Lucky', 'Unlucky', 'Planned', 'Expected'],
    'correctAnswer': 'Lucky',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for impetuous',
    'options': ['Impulsive', 'Careful', 'Cautious', 'Thoughtful'],
    'correctAnswer': 'Impulsive',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for keen',
    'options': ['Eager', 'Lazy', 'Disinterested', 'Indifferent'],
    'correctAnswer': 'Eager',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for loquacious',
    'options': ['Talkative', 'Quiet', 'Shy', 'Reserved'],
    'correctAnswer': 'Talkative',
    'type': 'synonym',
  },
  {
    'word': 'Meaning of gregarious',
    'options': ['Sociable', 'Shy', 'Reserved', 'Quiet'],
    'correctAnswer': 'Sociable',
    'type': 'definition',
  },
  {
    'word': 'Meaning of impetuous',
    'options': ['Impulsive', 'Careful', 'Cautious', 'Thoughtful'],
    'correctAnswer': 'Impulsive',
    'type': 'definition',
  },
  {
    'word': 'Meaning of loquacious',
    'options': ['Talkative', 'Silent', 'Quiet', 'Shy'],
    'correctAnswer': 'Talkative',
    'type': 'definition',
  },

  {
    'word': 'Meaning of judicious',
    'options': ['Wise', 'Foolish', 'Careless', 'Impulsive'],
    'correctAnswer': 'Wise',
    'type': 'definition',
  },
  {
    'word': 'Synonym for garrulous',
    'options': ['Talkative', 'Quiet', 'Shy', 'Reserved'],
    'correctAnswer': 'Talkative',
    'type': 'synonym',
  },
  {
    'word': 'Synonym for harbinger',
    'options': ['Forerunner', 'Follower', 'Latecomer', 'Unknown'],
    'correctAnswer': 'Forerunner',
    'type': 'synonym',
  },
  {
    'word': 'Antonym for recalcitrant',
    'options': ['Compliant', 'Disobedient', 'Obstinate', 'Defiant'],
    'correctAnswer': 'Compliant',
    'type': 'antonym',
  },
  {
    'word': 'Meaning of hackneyed',
    'options': ['Overused', 'Original', 'Unique', 'Rare'],
    'correctAnswer': 'Overused',
    'type': 'definition',
  },

  {
    'word': 'Antonym for keen',
    'options': ['Indifferent', 'Eager', 'Excited', 'Happy'],
    'correctAnswer': 'Indifferent',
    'type': 'antonym',
  },
];
